"""add_tasks_table

Revision ID: 21cfdfadc4b3
Revises: 0880f7bb3526
Create Date: 2026-02-07 01:36:02.337175

Creates the tasks table for tracking async operations (RAG ingestion, etc.).
Also cleans up legacy Celery metadata tables.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21cfdfadc4b3'
down_revision: Union[str, None] = '0880f7bb3526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True, comment='Celery task ID for tracking'),
    sa.Column('task_type', sa.Enum('document_ingestion', 'embedding_generation', 'document_deletion', name='task_type', create_constraint=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'STARTED', 'PROGRESS', 'SUCCESS', 'FAILURE', 'REVOKED', 'RETRY', name='task_status', create_constraint=True), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False, comment='Human-readable task name'),
    sa.Column('task_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Task arguments (for debugging)'),
    sa.Column('progress_current', sa.Integer(), nullable=True, comment='Current progress value'),
    sa.Column('progress_total', sa.Integer(), nullable=True, comment='Total progress value'),
    sa.Column('progress_message', sa.String(length=500), nullable=True, comment='Human-readable progress message'),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Task result (on success)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error details (on failure)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_celery_task_id'), 'tasks', ['celery_task_id'], unique=True)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    # Drop legacy Celery metadata tables if they exist
    op.execute("DROP TABLE IF EXISTS celery_tasksetmeta CASCADE")
    op.execute("DROP TABLE IF EXISTS celery_taskmeta CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tasks table and indexes
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_celery_task_id'), table_name='tasks')
    op.drop_table('tasks')
    
    # Drop enum types
    op.execute("DROP TYPE IF EXISTS task_type")
    op.execute("DROP TYPE IF EXISTS task_status")
    # ### end Alembic commands ###
