"""add_conversation_type_to_conversations

Revision ID: dd4449dc849d
Revises: 2c7a818c3a22
Create Date: 2026-02-08 11:35:38.432307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd4449dc849d'
down_revision: Union[str, None] = '2c7a818c3a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('conversation_type', sa.String(length=50), nullable=False, server_default='nlq'))
    op.create_index(op.f('ix_conversations_conversation_type'), 'conversations', ['conversation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_conversation_type'), table_name='conversations')
    op.drop_column('conversations', 'conversation_type')
    # ### end Alembic commands ###
